/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongRouteImport } from './routes/wrong'
import { Route as WishRouteImport } from './routes/wish'
import { Route as WatchingRouteImport } from './routes/watching'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SmileLiarRouteImport } from './routes/smile-liar'
import { Route as SmileRouteImport } from './routes/smile'
import { Route as ShortRouteImport } from './routes/short'
import { Route as PresentSadRouteImport } from './routes/present-sad'
import { Route as PresentHappyRouteImport } from './routes/present-happy'
import { Route as PresentRouteImport } from './routes/present'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MagicCornerRouteImport } from './routes/magic-corner'
import { Route as LiarRouteImport } from './routes/liar'
import { Route as FinalRouteImport } from './routes/final'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as AgeRouteImport } from './routes/age'
import { Route as IndexRouteImport } from './routes/index'

const WrongRoute = WrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const WishRoute = WishRouteImport.update({
  id: '/wish',
  path: '/wish',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchingRoute = WatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SmileLiarRoute = SmileLiarRouteImport.update({
  id: '/smile-liar',
  path: '/smile-liar',
  getParentRoute: () => rootRouteImport,
} as any)
const SmileRoute = SmileRouteImport.update({
  id: '/smile',
  path: '/smile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortRoute = ShortRouteImport.update({
  id: '/short',
  path: '/short',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentSadRoute = PresentSadRouteImport.update({
  id: '/present-sad',
  path: '/present-sad',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentHappyRoute = PresentHappyRouteImport.update({
  id: '/present-happy',
  path: '/present-happy',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicCornerRoute = MagicCornerRouteImport.update({
  id: '/magic-corner',
  path: '/magic-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const LiarRoute = LiarRouteImport.update({
  id: '/liar',
  path: '/liar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRoute = AgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/birthday': typeof BirthdayRoute
  '/final': typeof FinalRoute
  '/liar': typeof LiarRoute
  '/magic-corner': typeof MagicCornerRoute
  '/memories': typeof MemoriesRoute
  '/present': typeof PresentRoute
  '/present-happy': typeof PresentHappyRoute
  '/present-sad': typeof PresentSadRoute
  '/short': typeof ShortRoute
  '/smile': typeof SmileRoute
  '/smile-liar': typeof SmileLiarRoute
  '/video': typeof VideoRoute
  '/watching': typeof WatchingRoute
  '/wish': typeof WishRoute
  '/wrong': typeof WrongRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/birthday': typeof BirthdayRoute
  '/final': typeof FinalRoute
  '/liar': typeof LiarRoute
  '/magic-corner': typeof MagicCornerRoute
  '/memories': typeof MemoriesRoute
  '/present': typeof PresentRoute
  '/present-happy': typeof PresentHappyRoute
  '/present-sad': typeof PresentSadRoute
  '/short': typeof ShortRoute
  '/smile': typeof SmileRoute
  '/smile-liar': typeof SmileLiarRoute
  '/video': typeof VideoRoute
  '/watching': typeof WatchingRoute
  '/wish': typeof WishRoute
  '/wrong': typeof WrongRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/birthday': typeof BirthdayRoute
  '/final': typeof FinalRoute
  '/liar': typeof LiarRoute
  '/magic-corner': typeof MagicCornerRoute
  '/memories': typeof MemoriesRoute
  '/present': typeof PresentRoute
  '/present-happy': typeof PresentHappyRoute
  '/present-sad': typeof PresentSadRoute
  '/short': typeof ShortRoute
  '/smile': typeof SmileRoute
  '/smile-liar': typeof SmileLiarRoute
  '/video': typeof VideoRoute
  '/watching': typeof WatchingRoute
  '/wish': typeof WishRoute
  '/wrong': typeof WrongRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age'
    | '/birthday'
    | '/final'
    | '/liar'
    | '/magic-corner'
    | '/memories'
    | '/present'
    | '/present-happy'
    | '/present-sad'
    | '/short'
    | '/smile'
    | '/smile-liar'
    | '/video'
    | '/watching'
    | '/wish'
    | '/wrong'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age'
    | '/birthday'
    | '/final'
    | '/liar'
    | '/magic-corner'
    | '/memories'
    | '/present'
    | '/present-happy'
    | '/present-sad'
    | '/short'
    | '/smile'
    | '/smile-liar'
    | '/video'
    | '/watching'
    | '/wish'
    | '/wrong'
  id:
    | '__root__'
    | '/'
    | '/age'
    | '/birthday'
    | '/final'
    | '/liar'
    | '/magic-corner'
    | '/memories'
    | '/present'
    | '/present-happy'
    | '/present-sad'
    | '/short'
    | '/smile'
    | '/smile-liar'
    | '/video'
    | '/watching'
    | '/wish'
    | '/wrong'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeRoute: typeof AgeRoute
  BirthdayRoute: typeof BirthdayRoute
  FinalRoute: typeof FinalRoute
  LiarRoute: typeof LiarRoute
  MagicCornerRoute: typeof MagicCornerRoute
  MemoriesRoute: typeof MemoriesRoute
  PresentRoute: typeof PresentRoute
  PresentHappyRoute: typeof PresentHappyRoute
  PresentSadRoute: typeof PresentSadRoute
  ShortRoute: typeof ShortRoute
  SmileRoute: typeof SmileRoute
  SmileLiarRoute: typeof SmileLiarRoute
  VideoRoute: typeof VideoRoute
  WatchingRoute: typeof WatchingRoute
  WishRoute: typeof WishRoute
  WrongRoute: typeof WrongRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong': {
      id: '/wrong'
      path: '/wrong'
      fullPath: '/wrong'
      preLoaderRoute: typeof WrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish': {
      id: '/wish'
      path: '/wish'
      fullPath: '/wish'
      preLoaderRoute: typeof WishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watching': {
      id: '/watching'
      path: '/watching'
      fullPath: '/watching'
      preLoaderRoute: typeof WatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smile-liar': {
      id: '/smile-liar'
      path: '/smile-liar'
      fullPath: '/smile-liar'
      preLoaderRoute: typeof SmileLiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smile': {
      id: '/smile'
      path: '/smile'
      fullPath: '/smile'
      preLoaderRoute: typeof SmileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short': {
      id: '/short'
      path: '/short'
      fullPath: '/short'
      preLoaderRoute: typeof ShortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present-sad': {
      id: '/present-sad'
      path: '/present-sad'
      fullPath: '/present-sad'
      preLoaderRoute: typeof PresentSadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present-happy': {
      id: '/present-happy'
      path: '/present-happy'
      fullPath: '/present-happy'
      preLoaderRoute: typeof PresentHappyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-corner': {
      id: '/magic-corner'
      path: '/magic-corner'
      fullPath: '/magic-corner'
      preLoaderRoute: typeof MagicCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liar': {
      id: '/liar'
      path: '/liar'
      fullPath: '/liar'
      preLoaderRoute: typeof LiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age': {
      id: '/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof AgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeRoute: AgeRoute,
  BirthdayRoute: BirthdayRoute,
  FinalRoute: FinalRoute,
  LiarRoute: LiarRoute,
  MagicCornerRoute: MagicCornerRoute,
  MemoriesRoute: MemoriesRoute,
  PresentRoute: PresentRoute,
  PresentHappyRoute: PresentHappyRoute,
  PresentSadRoute: PresentSadRoute,
  ShortRoute: ShortRoute,
  SmileRoute: SmileRoute,
  SmileLiarRoute: SmileLiarRoute,
  VideoRoute: VideoRoute,
  WatchingRoute: WatchingRoute,
  WishRoute: WishRoute,
  WrongRoute: WrongRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
